# Generated by Django 4.1.7 on 2023-06-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_allow_fl_access_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='allow_fl_access',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
