# Generated by Django 4.1.7 on 2023-06-19 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_contactmessage_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Hopital', 'Hopital'), ('Doctor', 'Doctor')], default='Hopital', max_length=10),
        ),
    ]
