# Generated by Django 4.1.7 on 2023-06-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_user_user_parent_user_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Doctor', 'Doctor')], default='Hospital', max_length=10),
        ),
    ]
