# Generated by Django 4.1.7 on 2023-04-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='patients')),
                ('description', models.TextField()),
                ('diagnostic', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
