# Generated by Django 4.1.7 on 2023-05-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_adress_patient_blood_type_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xray_image', models.ImageField(blank=True, null=True, upload_to='xray_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xray_images', to='patients.patient')),
            ],
        ),
    ]
