# Generated by Django 4.1.7 on 2023-06-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_xrayimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='diagnostic',
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
