# Generated by Django 4.1.7 on 2023-06-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patient_diagnostic_xrayimage_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='type',
            field=models.CharField(choices=[('multiclass', 'multiclass'), ('pneumonia', 'pneumonia')], default='multiclass', max_length=10),
        ),
    ]
