# Generated by Django 4.1.7 on 2023-06-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_xrayimage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xrayimage',
            name='type',
        ),
    ]
