# Generated by Django 4.1.7 on 2023-06-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_xrayimage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
