# Generated by Django 4.1.7 on 2023-06-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patient_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='secret_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
