# Generated by Django 4.1.7 on 2023-06-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl', '0002_flresults_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flresults',
            name='gender',
        ),
        migrations.AddField(
            model_name='flresults',
            name='algo',
            field=models.CharField(choices=[('Pneumonia', 'Pneumonia'), ('Multiclass', 'Multiclass')], default='Pneumonia', max_length=10),
        ),
    ]
