FROM python:3.9

# 
WORKDIR /api

# 
COPY ./requirements.txt /api/requirements.txt

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

# 
RUN pip install --no-cache-dir --upgrade -r /api/requirements.txt

# 
COPY . /api/

# 
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000"]